### ISSUE TITLE
admin模板中users.hbs报错 v1.31.0 for docker

### ISSUE THREAD

**Issue by i-Eureka** [wcjxixi/vaultwarden-lang-zhcn#1]
`[2024-07-16 21:40:17.104][error][ERROR] Handlebars.
[CAUSE] RenderError {
    template_name: Some(
        "admin/users",
    ),
    line_no: Some(
        21,
    ),
    column_no: Some(
        112,
    ),
    reason: MissingVariable(
        Some(
            "Email",
        ),
    ),
    unimplemented: false,
}
`

**Comment by wcjxixi** [comment]
admin 模版仅适用于 [v1.30.5](https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.5)，暂不适用于最新的 [v1.31.0](https://github.com/dani-garcia/vaultwarden/releases/tag/1.31.0)
